source "https://rubygems.org"

ruby "3.4.4"

gem "rails", "~> 7.2.2"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "bootsnap", ">= 1.4.4", require: false

# API Gems
gem "active_model_serializers"
gem "rack-cors"

# Authentication and Authorization Gems
gem "devise"
gem "devise-jwt"
gem "pundit"

# Asynchronous Task Gems
gem "redis"
gem "sidekiq"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "rswag-api"
  gem "rswag-specs"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rswag-ui"
end
